
{% set data = load_setup_py_data() %}

package:
    name: nn_fdk
    
    version: {{ data['version'] }}

source:
    path: ../

build:
    number: '0'

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: https://github.com/mjlagerwerf/nn_fdk
    license_file: LICENSE.md
    summary: "Support code for the Neural Network FDK algorithm paper"

extra:
    maintainers:
        - Rien Lagerwerf
